### ISSUE TITLE
[bug] Verbindungsfehler Leica TS07 zu Lenovo Thinkpad

### ISSUE THREAD

**Issue by DeMelkor** [gbv/Tachy2GIS#5]
Wie besprochen hier noch die Fehlermeldung. Auf dem Surface Pro 8 klappt es übrigens ohne Probleme, haben wir heute getestet.

```
Python Stack Trace
Windows fatal exception: access violation

Current thread 0x000021a0 (most recent call first):
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\tachyconnect\ts_control.py", line 316 in __init__
    self.serial.writeData(message.encode('ascii'))
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\tachyconnect\ts_control.py", line 243 in moin
    ping = Ping(port_names.pop(), 500)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\tachyconnect\ts_control.py", line 337 in read
    self.timed_out.emit(f"Ping timed out: {self.serial.portName()}")
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\tachyconnect\ts_control.py", line 325 in fire
    self.ping_loop.exec_()
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\tachyconnect\ts_control.py", line 246 in moin
    ping.fire()
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\tachyconnect\ts_control.py", line 247 in hook_up
    moin()


Stack Trace
No stack trace is available.


QGIS Info
QGIS Version: 3.24.2-Tisler
QGIS code revision: 13c1a028
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.2
Running against GDAL: 3.4.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042
```

**Comment by ChristofSchubert** [comment]
Wir haben das selbe Problem mit einer unserer TS07 in Kombination mit einem Dell 7424 (Verbindung sowohl per Bluetooth als auch per USB-Kabel (Leica GEV267) getestet). Mit einem anderen Dell 7424 lässt sich die selbe TS problemlos verbinden.

**Comment by chris-jan-trapp** [comment]
The reason behind this was a programming error. The detection logic probed every serial port and tried to open it to write a request. It didn't check whether opening the port had actually been successful. That resulted in access violations, which occurred depending of the order in which ports were probed. This should be fixed in version [0.4.1](https://pypi.org/project/tachyconnect/), please update your tachyconnect version in the OSGeo4Win shell and report back.

**Comment by DeMelkor** [comment]
Thank you for the new version. We have tested three devices with it and the Surface Pro 8 and the Dell computer work very well with version 0.4.1.
However, it still does not connect on our Lenovo Think-Pad. (unfortunately most of our machines) There is one change though and that is T2G no longer crashes when you click connect. You can still use all the functions of T2G but there is no message about why the connection is not working. (Also no Python logs etc.) The connection of the Lenovo with the old version without 3D-Viewer of T2G works. can we still test or do something to support you?

**Comment by chris-jan-trapp** [comment]
I also experienced the non crashing failure to connect with my machine and solved it completely outside T2G and tachyconnect by disabling the onboard bluetooth adapter in the device manager and plugging in an older cheap USB dongle I had lying around. My assumption is that the root cause of this problem can be found in the OS/ drivers layer, because I remember having used the onboard adapter earlier last year. I'll see if I can identify manufacturer and model or at least the chipset of the Dongle when I'm back in my home- office on Friday.

**Comment by chris-jan-trapp** [comment]
My BT dongle is a Speedlink SL-7411-BK, which contains the widely used Cambridge Silicon Radio CSR8510 A10 chipset.

**Comment by DeMelkor** [comment]
Thank you for the dongle recommendation. We were also able to solve the problem on another Lenovo by removing all other Bluetooth devices, then connecting the Tachy and the connection worked. The headphones first occupied Com 3-4 and the tachy 6-7. After the changeover, which worked, the tachy occupied 3-4.
